[kungfu-prun] 2019/04/05 16:23:44 args[0]=/KungFu/bin/kungfu-prun
[kungfu-prun] 2019/04/05 16:23:44 args[1]=-np=4
[kungfu-prun] 2019/04/05 16:23:44 args[2]=-timeout=10m
[kungfu-prun] 2019/04/05 16:23:44 args[3]=python3
[kungfu-prun] 2019/04/05 16:23:44 args[4]=./benchmarks/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks_kungfu.py
[kungfu-prun] 2019/04/05 16:23:44 args[5]=--num_gpus=1
[kungfu-prun] 2019/04/05 16:23:44 args[6]=--batch_size=32
[kungfu-prun] 2019/04/05 16:23:44 args[7]=--model=resnet50
[kungfu-prun] 2019/04/05 16:23:44 args[8]=--variable_update=kungfu
[kungfu-prun] 2019/04/05 16:23:44 args[9]=--ako_partitions=49
[kungfu-prun] 2019/04/05 16:23:44 Using selfHost=127.0.0.1
[kungfu-prun] 2019/04/05 16:23:44 will parallel run 4 instances of python3 with ["./benchmarks/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks_kungfu.py" "--num_gpus=1" "--batch_size=32" "--model=resnet50" "--variable_update=kungfu" "--ako_partitions=49"]
[[1;33m127.0.0.1/02/02-of-04[m::stderr] 2019-04-05 16:23:47.770703: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
[[1;36m127.0.0.1/03/03-of-04[m::stderr] 2019-04-05 16:23:47.771226: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
[[1;34m127.0.0.1/01/01-of-04[m::stderr] 2019-04-05 16:23:47.860642: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
[[1;32m127.0.0.1/00/00-of-04[m::stderr] 2019-04-05 16:23:47.913517: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
[[1;36m127.0.0.1/03/03-of-04[m::stderr] 2019-04-05 16:23:48.107331: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
[[1;36m127.0.0.1/03/03-of-04[m::stderr] name: TITAN X (Pascal) major: 6 minor: 1 memoryClockRate(GHz): 1.531
[[1;36m127.0.0.1/03/03-of-04[m::stderr] pciBusID: 0000:84:00.0
[[1;36m127.0.0.1/03/03-of-04[m::stderr] totalMemory: 11.91GiB freeMemory: 11.77GiB
[[1;36m127.0.0.1/03/03-of-04[m::stderr] 2019-04-05 16:23:48.107372: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
[[1;33m127.0.0.1/02/02-of-04[m::stderr] 2019-04-05 16:23:48.155679: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
[[1;33m127.0.0.1/02/02-of-04[m::stderr] name: TITAN X (Pascal) major: 6 minor: 1 memoryClockRate(GHz): 1.531
[[1;33m127.0.0.1/02/02-of-04[m::stderr] pciBusID: 0000:83:00.0
[[1;33m127.0.0.1/02/02-of-04[m::stderr] totalMemory: 11.91GiB freeMemory: 11.77GiB
[[1;33m127.0.0.1/02/02-of-04[m::stderr] 2019-04-05 16:23:48.155758: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
[[1;34m127.0.0.1/01/01-of-04[m::stderr] 2019-04-05 16:23:48.241389: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
[[1;34m127.0.0.1/01/01-of-04[m::stderr] name: TITAN X (Pascal) major: 6 minor: 1 memoryClockRate(GHz): 1.531
[[1;34m127.0.0.1/01/01-of-04[m::stderr] pciBusID: 0000:03:00.0
[[1;34m127.0.0.1/01/01-of-04[m::stderr] totalMemory: 11.91GiB freeMemory: 11.77GiB
[[1;34m127.0.0.1/01/01-of-04[m::stderr] 2019-04-05 16:23:48.241437: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
[[1;32m127.0.0.1/00/00-of-04[m::stderr] 2019-04-05 16:23:48.251931: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
[[1;32m127.0.0.1/00/00-of-04[m::stderr] name: TITAN X (Pascal) major: 6 minor: 1 memoryClockRate(GHz): 1.531
[[1;32m127.0.0.1/00/00-of-04[m::stderr] pciBusID: 0000:02:00.0
[[1;32m127.0.0.1/00/00-of-04[m::stderr] totalMemory: 11.91GiB freeMemory: 11.77GiB
[[1;32m127.0.0.1/00/00-of-04[m::stderr] 2019-04-05 16:23:48.251973: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
[[1;36m127.0.0.1/03/03-of-04[m::stderr] 2019-04-05 16:23:48.583410: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
[[1;36m127.0.0.1/03/03-of-04[m::stderr] 2019-04-05 16:23:48.583464: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
[[1;36m127.0.0.1/03/03-of-04[m::stderr] 2019-04-05 16:23:48.583472: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
[[1;36m127.0.0.1/03/03-of-04[m::stderr] 2019-04-05 16:23:48.584039: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 11385 MB memory) -> physical GPU (device: 0, name: TITAN X (Pascal), pci bus id: 0000:84:00.0, compute capability: 6.1)
[[1;36m127.0.0.1/03/03-of-04[m::stdout] TensorFlow:  1.12
[[1;36m127.0.0.1/03/03-of-04[m::stdout] Model:       resnet50
[[1;36m127.0.0.1/03/03-of-04[m::stdout] Dataset:     imagenet (synthetic)
[[1;36m127.0.0.1/03/03-of-04[m::stdout] Mode:        BenchmarkMode.TRAIN
[[1;36m127.0.0.1/03/03-of-04[m::stdout] SingleSess:  False
[[1;36m127.0.0.1/03/03-of-04[m::stdout] Batch size:  128 global
[[1;36m127.0.0.1/03/03-of-04[m::stdout]              32.0 per device
[[1;36m127.0.0.1/03/03-of-04[m::stdout] Num batches: 200
[[1;36m127.0.0.1/03/03-of-04[m::stdout] Num epochs:  0.02
[[1;36m127.0.0.1/03/03-of-04[m::stdout] Devices:     ['/gpu:0']
[[1;36m127.0.0.1/03/03-of-04[m::stdout] Data format: NCHW
[[1;36m127.0.0.1/03/03-of-04[m::stdout] Optimizer:   sgd
[[1;36m127.0.0.1/03/03-of-04[m::stdout] Variables:   kungfu
[[1;36m127.0.0.1/03/03-of-04[m::stdout] ==========
[[1;36m127.0.0.1/03/03-of-04[m::stdout] Generating training model
[[1;33m127.0.0.1/02/02-of-04[m::stderr] 2019-04-05 16:23:48.694513: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
[[1;33m127.0.0.1/02/02-of-04[m::stderr] 2019-04-05 16:23:48.694564: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
[[1;33m127.0.0.1/02/02-of-04[m::stderr] 2019-04-05 16:23:48.694571: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
[[1;33m127.0.0.1/02/02-of-04[m::stderr] 2019-04-05 16:23:48.695151: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 11385 MB memory) -> physical GPU (device: 0, name: TITAN X (Pascal), pci bus id: 0000:83:00.0, compute capability: 6.1)
[[1;33m127.0.0.1/02/02-of-04[m::stdout] TensorFlow:  1.12
[[1;33m127.0.0.1/02/02-of-04[m::stdout] Model:       resnet50
[[1;33m127.0.0.1/02/02-of-04[m::stdout] Dataset:     imagenet (synthetic)
[[1;33m127.0.0.1/02/02-of-04[m::stdout] Mode:        BenchmarkMode.TRAIN
[[1;33m127.0.0.1/02/02-of-04[m::stdout] SingleSess:  False
[[1;33m127.0.0.1/02/02-of-04[m::stdout] Batch size:  128 global
[[1;33m127.0.0.1/02/02-of-04[m::stdout]              32.0 per device
[[1;33m127.0.0.1/02/02-of-04[m::stdout] Num batches: 200
[[1;33m127.0.0.1/02/02-of-04[m::stdout] Num epochs:  0.02
[[1;33m127.0.0.1/02/02-of-04[m::stdout] Devices:     ['/gpu:0']
[[1;33m127.0.0.1/02/02-of-04[m::stdout] Data format: NCHW
[[1;33m127.0.0.1/02/02-of-04[m::stdout] Optimizer:   sgd
[[1;33m127.0.0.1/02/02-of-04[m::stdout] Variables:   kungfu
[[1;33m127.0.0.1/02/02-of-04[m::stdout] ==========
[[1;33m127.0.0.1/02/02-of-04[m::stdout] Generating training model
[[1;34m127.0.0.1/01/01-of-04[m::stderr] 2019-04-05 16:23:48.718304: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
[[1;34m127.0.0.1/01/01-of-04[m::stderr] 2019-04-05 16:23:48.718370: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
[[1;34m127.0.0.1/01/01-of-04[m::stderr] 2019-04-05 16:23:48.718379: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
[[1;34m127.0.0.1/01/01-of-04[m::stderr] 2019-04-05 16:23:48.718996: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 11385 MB memory) -> physical GPU (device: 0, name: TITAN X (Pascal), pci bus id: 0000:03:00.0, compute capability: 6.1)
[[1;34m127.0.0.1/01/01-of-04[m::stdout] TensorFlow:  1.12
[[1;34m127.0.0.1/01/01-of-04[m::stdout] Model:       resnet50
[[1;34m127.0.0.1/01/01-of-04[m::stdout] Dataset:     imagenet (synthetic)
[[1;34m127.0.0.1/01/01-of-04[m::stdout] Mode:        BenchmarkMode.TRAIN
[[1;34m127.0.0.1/01/01-of-04[m::stdout] SingleSess:  False
[[1;34m127.0.0.1/01/01-of-04[m::stdout] Batch size:  128 global
[[1;34m127.0.0.1/01/01-of-04[m::stdout]              32.0 per device
[[1;34m127.0.0.1/01/01-of-04[m::stdout] Num batches: 200
[[1;34m127.0.0.1/01/01-of-04[m::stdout] Num epochs:  0.02
[[1;34m127.0.0.1/01/01-of-04[m::stdout] Devices:     ['/gpu:0']
[[1;34m127.0.0.1/01/01-of-04[m::stdout] Data format: NCHW
[[1;34m127.0.0.1/01/01-of-04[m::stdout] Optimizer:   sgd
[[1;34m127.0.0.1/01/01-of-04[m::stdout] Variables:   kungfu
[[1;34m127.0.0.1/01/01-of-04[m::stdout] ==========
[[1;34m127.0.0.1/01/01-of-04[m::stdout] Generating training model
[[1;32m127.0.0.1/00/00-of-04[m::stderr] 2019-04-05 16:23:48.751648: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
[[1;32m127.0.0.1/00/00-of-04[m::stderr] 2019-04-05 16:23:48.751709: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
[[1;32m127.0.0.1/00/00-of-04[m::stderr] 2019-04-05 16:23:48.751717: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
[[1;32m127.0.0.1/00/00-of-04[m::stderr] 2019-04-05 16:23:48.752379: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 11385 MB memory) -> physical GPU (device: 0, name: TITAN X (Pascal), pci bus id: 0000:02:00.0, compute capability: 6.1)
[[1;32m127.0.0.1/00/00-of-04[m::stdout] TensorFlow:  1.12
[[1;32m127.0.0.1/00/00-of-04[m::stdout] Model:       resnet50
[[1;32m127.0.0.1/00/00-of-04[m::stdout] Dataset:     imagenet (synthetic)
[[1;32m127.0.0.1/00/00-of-04[m::stdout] Mode:        BenchmarkMode.TRAIN
[[1;32m127.0.0.1/00/00-of-04[m::stdout] SingleSess:  False
[[1;32m127.0.0.1/00/00-of-04[m::stdout] Batch size:  128 global
[[1;32m127.0.0.1/00/00-of-04[m::stdout]              32.0 per device
[[1;32m127.0.0.1/00/00-of-04[m::stdout] Num batches: 200
[[1;32m127.0.0.1/00/00-of-04[m::stdout] Num epochs:  0.02
[[1;32m127.0.0.1/00/00-of-04[m::stdout] Devices:     ['/gpu:0']
[[1;32m127.0.0.1/00/00-of-04[m::stdout] Data format: NCHW
[[1;32m127.0.0.1/00/00-of-04[m::stdout] Optimizer:   sgd
[[1;32m127.0.0.1/00/00-of-04[m::stdout] Variables:   kungfu
[[1;32m127.0.0.1/00/00-of-04[m::stdout] ==========
[[1;32m127.0.0.1/00/00-of-04[m::stdout] Generating training model
[[1;36m127.0.0.1/03/03-of-04[m::stdout] kungfu_tensorflow_init_gpu FAILED: /root/.local/lib/python3.5/site-packages/kungfu/libkungfu_tensorflow_init.so: undefined symbol: kungfu_tensorflow_init_gpu
[[1;33m127.0.0.1/02/02-of-04[m::stdout] kungfu_tensorflow_init_gpu FAILED: /root/.local/lib/python3.5/site-packages/kungfu/libkungfu_tensorflow_init.so: undefined symbol: kungfu_tensorflow_init_gpu
[[1;32m127.0.0.1/00/00-of-04[m::stdout] kungfu_tensorflow_init_gpu FAILED: /root/.local/lib/python3.5/site-packages/kungfu/libkungfu_tensorflow_init.so: undefined symbol: kungfu_tensorflow_init_gpu
[[1;34m127.0.0.1/01/01-of-04[m::stdout] kungfu_tensorflow_init_gpu FAILED: /root/.local/lib/python3.5/site-packages/kungfu/libkungfu_tensorflow_init.so: undefined symbol: kungfu_tensorflow_init_gpu
[[1;36m127.0.0.1/03/03-of-04[m::stderr] Traceback (most recent call last):
[[1;36m127.0.0.1/03/03-of-04[m::stderr]   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1628, in _create_c_op
[[1;36m127.0.0.1/03/03-of-04[m::stderr]     c_op = c_api.TF_FinishOperation(op_desc)
[[1;36m127.0.0.1/03/03-of-04[m::stderr] tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension 0 in both shapes must be equal, but are 512 and 64. Shapes are [512] and [64]. for 'append_apply_gradient_ops/GradientDescent/update_v0/cg/resnet_v115/conv51/batchnorm51/gamma/ApplyGradientDescent' (op: 'ApplyGradientDescent') with input shapes: [512], [], [64].
[[1;36m127.0.0.1/03/03-of-04[m::stderr] 
[[1;36m127.0.0.1/03/03-of-04[m::stderr] During handling of the above exception, another exception occurred:
[[1;36m127.0.0.1/03/03-of-04[m::stderr] 
[[1;36m127.0.0.1/03/03-of-04[m::stderr] Traceback (most recent call last):
[[1;36m127.0.0.1/03/03-of-04[m::stderr]   File "./benchmarks/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks_kungfu.py", line 61, in <module>
[[1;36m127.0.0.1/03/03-of-04[m::stderr]     app.run(main)  # Raises error on invalid flags, unlike tf.app.run()
[[1;36m127.0.0.1/03/03-of-04[m::stderr]   File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 300, in run
[[1;36m127.0.0.1/03/03-of-04[m::stderr]     _run_main(main, args)
[[1;36m127.0.0.1/03/03-of-04[m::stderr]   File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 251, in _run_main
[[1;36m127.0.0.1/03/03-of-04[m::stderr]     sys.exit(main(argv))
[[1;36m127.0.0.1/03/03-of-04[m::stderr]   File "./benchmarks/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks_kungfu.py", line 57, in main
[[1;36m127.0.0.1/03/03-of-04[m::stderr]     bench.run()
[[1;36m127.0.0.1/03/03-of-04[m::stderr]   File "/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn_kungfu.py", line 1792, in run
[[1;36m127.0.0.1/03/03-of-04[m::stderr]     return self._benchmark_train()
[[1;36m127.0.0.1/03/03-of-04[m::stderr]   File "/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn_kungfu.py", line 1975, in _benchmark_train
[[1;36m127.0.0.1/03/03-of-04[m::stderr]     build_result = self._build_graph()
[[1;36m127.0.0.1/03/03-of-04[m::stderr]   File "/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn_kungfu.py", line 2009, in _build_graph
[[1;36m127.0.0.1/03/03-of-04[m::stderr]     (input_producer_op, enqueue_ops, fetches) = self._build_model()
[[1;36m127.0.0.1/03/03-of-04[m::stderr]   File "/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn_kungfu.py", line 2762, in _build_model
[[1;36m127.0.0.1/03/03-of-04[m::stderr]     phase_train)
[[1;36m127.0.0.1/03/03-of-04[m::stderr]   File "/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn_kungfu.py", line 2840, in _build_fetches
[[1;36m127.0.0.1/03/03-of-04[m::stderr]     loss_scale_params)
[[1;36m127.0.0.1/03/03-of-04[m::stderr]   File "/benchmarks/scripts/tf_cnn_benchmarks/variable_mgr.py", line 110, in append_apply_gradients_ops
[[1;36m127.0.0.1/03/03-of-04[m::stderr]     self.grad_has_inf_nan)
[[1;36m127.0.0.1/03/03-of-04[m::stderr]   File "/benchmarks/scripts/tf_cnn_benchmarks/variable_mgr_util.py", line 112, in append_gradients_with_loss_scale
[[1;36m127.0.0.1/03/03-of-04[m::stderr]     training_ops.extend(get_apply_gradients_ops_func())
[[1;36m127.0.0.1/03/03-of-04[m::stderr]   File "/benchmarks/scripts/tf_cnn_benchmarks/variable_mgr.py", line 106, in get_apply_gradients_ops_func
[[1;36m127.0.0.1/03/03-of-04[m::stderr]     return [opt.apply_gradients(grads)]
[[1;36m127.0.0.1/03/03-of-04[m::stderr]   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/optimizer.py", line 610, in apply_gradients
[[1;36m127.0.0.1/03/03-of-04[m::stderr]     update_ops.append(processor.update_op(self, grad))
[[1;36m127.0.0.1/03/03-of-04[m::stderr]   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/optimizer.py", line 115, in update_op
[[1;36m127.0.0.1/03/03-of-04[m::stderr]     update_op = optimizer._apply_dense(g, self._v)  # pylint: disable=protected-access
[[1;36m127.0.0.1/03/03-of-04[m::stderr]   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/gradient_descent.py", line 60, in _apply_dense
[[1;36m127.0.0.1/03/03-of-04[m::stderr]     use_locking=self._use_locking).op
[[1;36m127.0.0.1/03/03-of-04[m::stderr]   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/gen_training_ops.py", line 577, in apply_gradient_descent
[[1;36m127.0.0.1/03/03-of-04[m::stderr]     use_locking=use_locking, name=name)
[[1;36m127.0.0.1/03/03-of-04[m::stderr]   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
[[1;36m127.0.0.1/03/03-of-04[m::stderr]     op_def=op_def)
[[1;36m127.0.0.1/03/03-of-04[m::stderr]   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
[[1;36m127.0.0.1/03/03-of-04[m::stderr]     return func(*args, **kwargs)
[[1;36m127.0.0.1/03/03-of-04[m::stderr]   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
[[1;36m127.0.0.1/03/03-of-04[m::stderr]     op_def=op_def)
[[1;36m127.0.0.1/03/03-of-04[m::stderr]   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1792, in __init__
[[1;36m127.0.0.1/03/03-of-04[m::stderr]     control_input_ops)
[[1;36m127.0.0.1/03/03-of-04[m::stderr]   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1631, in _create_c_op
[[1;36m127.0.0.1/03/03-of-04[m::stderr]     raise ValueError(str(e))
[[1;36m127.0.0.1/03/03-of-04[m::stderr] ValueError: Dimension 0 in both shapes must be equal, but are 512 and 64. Shapes are [512] and [64]. for 'append_apply_gradient_ops/GradientDescent/update_v0/cg/resnet_v115/conv51/batchnorm51/gamma/ApplyGradientDescent' (op: 'ApplyGradientDescent') with input shapes: [512], [], [64].
[[1;33m127.0.0.1/02/02-of-04[m::stderr] Traceback (most recent call last):
[[1;33m127.0.0.1/02/02-of-04[m::stderr]   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1628, in _create_c_op
[[1;33m127.0.0.1/02/02-of-04[m::stderr]     c_op = c_api.TF_FinishOperation(op_desc)
[[1;33m127.0.0.1/02/02-of-04[m::stderr] tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension 0 in both shapes must be equal, but are 512 and 64. Shapes are [512] and [64]. for 'append_apply_gradient_ops/GradientDescent/update_v0/cg/resnet_v115/conv51/batchnorm51/gamma/ApplyGradientDescent' (op: 'ApplyGradientDescent') with input shapes: [512], [], [64].
[[1;33m127.0.0.1/02/02-of-04[m::stderr] 
[[1;33m127.0.0.1/02/02-of-04[m::stderr] During handling of the above exception, another exception occurred:
[[1;33m127.0.0.1/02/02-of-04[m::stderr] 
[[1;33m127.0.0.1/02/02-of-04[m::stderr] Traceback (most recent call last):
[[1;33m127.0.0.1/02/02-of-04[m::stderr]   File "./benchmarks/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks_kungfu.py", line 61, in <module>
[[1;33m127.0.0.1/02/02-of-04[m::stderr]     app.run(main)  # Raises error on invalid flags, unlike tf.app.run()
[[1;33m127.0.0.1/02/02-of-04[m::stderr]   File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 300, in run
[[1;33m127.0.0.1/02/02-of-04[m::stderr]     _run_main(main, args)
[[1;33m127.0.0.1/02/02-of-04[m::stderr]   File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 251, in _run_main
[[1;33m127.0.0.1/02/02-of-04[m::stderr]     sys.exit(main(argv))
[[1;33m127.0.0.1/02/02-of-04[m::stderr]   File "./benchmarks/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks_kungfu.py", line 57, in main
[[1;33m127.0.0.1/02/02-of-04[m::stderr]     bench.run()
[[1;33m127.0.0.1/02/02-of-04[m::stderr]   File "/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn_kungfu.py", line 1792, in run
[[1;33m127.0.0.1/02/02-of-04[m::stderr]     return self._benchmark_train()
[[1;33m127.0.0.1/02/02-of-04[m::stderr]   File "/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn_kungfu.py", line 1975, in _benchmark_train
[[1;33m127.0.0.1/02/02-of-04[m::stderr]     build_result = self._build_graph()
[[1;33m127.0.0.1/02/02-of-04[m::stderr]   File "/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn_kungfu.py", line 2009, in _build_graph
[[1;33m127.0.0.1/02/02-of-04[m::stderr]     (input_producer_op, enqueue_ops, fetches) = self._build_model()
[[1;33m127.0.0.1/02/02-of-04[m::stderr]   File "/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn_kungfu.py", line 2762, in _build_model
[[1;33m127.0.0.1/02/02-of-04[m::stderr]     phase_train)
[[1;33m127.0.0.1/02/02-of-04[m::stderr]   File "/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn_kungfu.py", line 2840, in _build_fetches
[[1;33m127.0.0.1/02/02-of-04[m::stderr]     loss_scale_params)
[[1;33m127.0.0.1/02/02-of-04[m::stderr]   File "/benchmarks/scripts/tf_cnn_benchmarks/variable_mgr.py", line 110, in append_apply_gradients_ops
[[1;33m127.0.0.1/02/02-of-04[m::stderr]     self.grad_has_inf_nan)
[[1;33m127.0.0.1/02/02-of-04[m::stderr]   File "/benchmarks/scripts/tf_cnn_benchmarks/variable_mgr_util.py", line 112, in append_gradients_with_loss_scale
[[1;33m127.0.0.1/02/02-of-04[m::stderr]     training_ops.extend(get_apply_gradients_ops_func())
[[1;33m127.0.0.1/02/02-of-04[m::stderr]   File "/benchmarks/scripts/tf_cnn_benchmarks/variable_mgr.py", line 106, in get_apply_gradients_ops_func
[[1;33m127.0.0.1/02/02-of-04[m::stderr]     return [opt.apply_gradients(grads)]
[[1;33m127.0.0.1/02/02-of-04[m::stderr]   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/optimizer.py", line 610, in apply_gradients
[[1;33m127.0.0.1/02/02-of-04[m::stderr]     update_ops.append(processor.update_op(self, grad))
[[1;33m127.0.0.1/02/02-of-04[m::stderr]   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/optimizer.py", line 115, in update_op
[[1;33m127.0.0.1/02/02-of-04[m::stderr]     update_op = optimizer._apply_dense(g, self._v)  # pylint: disable=protected-access
[[1;33m127.0.0.1/02/02-of-04[m::stderr]   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/gradient_descent.py", line 60, in _apply_dense
[[1;33m127.0.0.1/02/02-of-04[m::stderr]     use_locking=self._use_locking).op
[[1;33m127.0.0.1/02/02-of-04[m::stderr]   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/gen_training_ops.py", line 577, in apply_gradient_descent
[[1;33m127.0.0.1/02/02-of-04[m::stderr]     use_locking=use_locking, name=name)
[[1;33m127.0.0.1/02/02-of-04[m::stderr]   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
[[1;33m127.0.0.1/02/02-of-04[m::stderr]     op_def=op_def)
[[1;33m127.0.0.1/02/02-of-04[m::stderr]   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
[[1;33m127.0.0.1/02/02-of-04[m::stderr]     return func(*args, **kwargs)
[[1;33m127.0.0.1/02/02-of-04[m::stderr]   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
[[1;33m127.0.0.1/02/02-of-04[m::stderr]     op_def=op_def)
[[1;33m127.0.0.1/02/02-of-04[m::stderr]   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1792, in __init__
[[1;33m127.0.0.1/02/02-of-04[m::stderr]     control_input_ops)
[[1;33m127.0.0.1/02/02-of-04[m::stderr]   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1631, in _create_c_op
[[1;33m127.0.0.1/02/02-of-04[m::stderr]     raise ValueError(str(e))
[[1;33m127.0.0.1/02/02-of-04[m::stderr] ValueError: Dimension 0 in both shapes must be equal, but are 512 and 64. Shapes are [512] and [64]. for 'append_apply_gradient_ops/GradientDescent/update_v0/cg/resnet_v115/conv51/batchnorm51/gamma/ApplyGradientDescent' (op: 'ApplyGradientDescent') with input shapes: [512], [], [64].
[[1;32m127.0.0.1/00/00-of-04[m::stderr] Traceback (most recent call last):
[[1;32m127.0.0.1/00/00-of-04[m::stderr]   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1628, in _create_c_op
[[1;32m127.0.0.1/00/00-of-04[m::stderr]     c_op = c_api.TF_FinishOperation(op_desc)
[[1;32m127.0.0.1/00/00-of-04[m::stderr] tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension 0 in both shapes must be equal, but are 512 and 64. Shapes are [512] and [64]. for 'append_apply_gradient_ops/GradientDescent/update_v0/cg/resnet_v115/conv51/batchnorm51/gamma/ApplyGradientDescent' (op: 'ApplyGradientDescent') with input shapes: [512], [], [64].
[[1;32m127.0.0.1/00/00-of-04[m::stderr] 
[[1;32m127.0.0.1/00/00-of-04[m::stderr] During handling of the above exception, another exception occurred:
[[1;32m127.0.0.1/00/00-of-04[m::stderr] 
[[1;32m127.0.0.1/00/00-of-04[m::stderr] Traceback (most recent call last):
[[1;32m127.0.0.1/00/00-of-04[m::stderr]   File "./benchmarks/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks_kungfu.py", line 61, in <module>
[[1;32m127.0.0.1/00/00-of-04[m::stderr]     app.run(main)  # Raises error on invalid flags, unlike tf.app.run()
[[1;32m127.0.0.1/00/00-of-04[m::stderr]   File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 300, in run
[[1;32m127.0.0.1/00/00-of-04[m::stderr]     _run_main(main, args)
[[1;32m127.0.0.1/00/00-of-04[m::stderr]   File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 251, in _run_main
[[1;32m127.0.0.1/00/00-of-04[m::stderr]     sys.exit(main(argv))
[[1;32m127.0.0.1/00/00-of-04[m::stderr]   File "./benchmarks/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks_kungfu.py", line 57, in main
[[1;32m127.0.0.1/00/00-of-04[m::stderr]     bench.run()
[[1;32m127.0.0.1/00/00-of-04[m::stderr]   File "/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn_kungfu.py", line 1792, in run
[[1;32m127.0.0.1/00/00-of-04[m::stderr]     return self._benchmark_train()
[[1;32m127.0.0.1/00/00-of-04[m::stderr]   File "/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn_kungfu.py", line 1975, in _benchmark_train
[[1;32m127.0.0.1/00/00-of-04[m::stderr]     build_result = self._build_graph()
[[1;32m127.0.0.1/00/00-of-04[m::stderr]   File "/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn_kungfu.py", line 2009, in _build_graph
[[1;32m127.0.0.1/00/00-of-04[m::stderr]     (input_producer_op, enqueue_ops, fetches) = self._build_model()
[[1;32m127.0.0.1/00/00-of-04[m::stderr]   File "/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn_kungfu.py", line 2762, in _build_model
[[1;32m127.0.0.1/00/00-of-04[m::stderr]     phase_train)
[[1;32m127.0.0.1/00/00-of-04[m::stderr]   File "/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn_kungfu.py", line 2840, in _build_fetches
[[1;32m127.0.0.1/00/00-of-04[m::stderr]     loss_scale_params)
[[1;32m127.0.0.1/00/00-of-04[m::stderr]   File "/benchmarks/scripts/tf_cnn_benchmarks/variable_mgr.py", line 110, in append_apply_gradients_ops
[[1;32m127.0.0.1/00/00-of-04[m::stderr]     self.grad_has_inf_nan)
[[1;32m127.0.0.1/00/00-of-04[m::stderr]   File "/benchmarks/scripts/tf_cnn_benchmarks/variable_mgr_util.py", line 112, in append_gradients_with_loss_scale
[[1;32m127.0.0.1/00/00-of-04[m::stderr]     training_ops.extend(get_apply_gradients_ops_func())
[[1;32m127.0.0.1/00/00-of-04[m::stderr]   File "/benchmarks/scripts/tf_cnn_benchmarks/variable_mgr.py", line 106, in get_apply_gradients_ops_func
[[1;32m127.0.0.1/00/00-of-04[m::stderr]     return [opt.apply_gradients(grads)]
[[1;32m127.0.0.1/00/00-of-04[m::stderr]   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/optimizer.py", line 610, in apply_gradients
[[1;32m127.0.0.1/00/00-of-04[m::stderr]     update_ops.append(processor.update_op(self, grad))
[[1;32m127.0.0.1/00/00-of-04[m::stderr]   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/optimizer.py", line 115, in update_op
[[1;32m127.0.0.1/00/00-of-04[m::stderr]     update_op = optimizer._apply_dense(g, self._v)  # pylint: disable=protected-access
[[1;32m127.0.0.1/00/00-of-04[m::stderr]   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/gradient_descent.py", line 60, in _apply_dense
[[1;32m127.0.0.1/00/00-of-04[m::stderr]     use_locking=self._use_locking).op
[[1;32m127.0.0.1/00/00-of-04[m::stderr]   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/gen_training_ops.py", line 577, in apply_gradient_descent
[[1;32m127.0.0.1/00/00-of-04[m::stderr]     use_locking=use_locking, name=name)
[[1;32m127.0.0.1/00/00-of-04[m::stderr]   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
[[1;32m127.0.0.1/00/00-of-04[m::stderr]     op_def=op_def)
[[1;32m127.0.0.1/00/00-of-04[m::stderr]   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
[[1;32m127.0.0.1/00/00-of-04[m::stderr]     return func(*args, **kwargs)
[[1;32m127.0.0.1/00/00-of-04[m::stderr]   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
[[1;32m127.0.0.1/00/00-of-04[m::stderr]     op_def=op_def)
[[1;32m127.0.0.1/00/00-of-04[m::stderr]   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1792, in __init__
[[1;32m127.0.0.1/00/00-of-04[m::stderr]     control_input_ops)
[[1;32m127.0.0.1/00/00-of-04[m::stderr]   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1631, in _create_c_op
[[1;32m127.0.0.1/00/00-of-04[m::stderr]     raise ValueError(str(e))
[[1;32m127.0.0.1/00/00-of-04[m::stderr] ValueError: Dimension 0 in both shapes must be equal, but are 512 and 64. Shapes are [512] and [64]. for 'append_apply_gradient_ops/GradientDescent/update_v0/cg/resnet_v115/conv51/batchnorm51/gamma/ApplyGradientDescent' (op: 'ApplyGradientDescent') with input shapes: [512], [], [64].
[[1;34m127.0.0.1/01/01-of-04[m::stderr] Traceback (most recent call last):
[[1;34m127.0.0.1/01/01-of-04[m::stderr]   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1628, in _create_c_op
[[1;34m127.0.0.1/01/01-of-04[m::stderr]     c_op = c_api.TF_FinishOperation(op_desc)
[[1;34m127.0.0.1/01/01-of-04[m::stderr] tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension 0 in both shapes must be equal, but are 512 and 64. Shapes are [512] and [64]. for 'append_apply_gradient_ops/GradientDescent/update_v0/cg/resnet_v115/conv51/batchnorm51/gamma/ApplyGradientDescent' (op: 'ApplyGradientDescent') with input shapes: [512], [], [64].
[[1;34m127.0.0.1/01/01-of-04[m::stderr] 
[[1;34m127.0.0.1/01/01-of-04[m::stderr] During handling of the above exception, another exception occurred:
[[1;34m127.0.0.1/01/01-of-04[m::stderr] 
[[1;34m127.0.0.1/01/01-of-04[m::stderr] Traceback (most recent call last):
[[1;34m127.0.0.1/01/01-of-04[m::stderr]   File "./benchmarks/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks_kungfu.py", line 61, in <module>
[[1;34m127.0.0.1/01/01-of-04[m::stderr]     app.run(main)  # Raises error on invalid flags, unlike tf.app.run()
[[1;34m127.0.0.1/01/01-of-04[m::stderr]   File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 300, in run
[[1;34m127.0.0.1/01/01-of-04[m::stderr]     _run_main(main, args)
[[1;34m127.0.0.1/01/01-of-04[m::stderr]   File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 251, in _run_main
[[1;34m127.0.0.1/01/01-of-04[m::stderr]     sys.exit(main(argv))
[[1;34m127.0.0.1/01/01-of-04[m::stderr]   File "./benchmarks/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks_kungfu.py", line 57, in main
[[1;34m127.0.0.1/01/01-of-04[m::stderr]     bench.run()
[[1;34m127.0.0.1/01/01-of-04[m::stderr]   File "/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn_kungfu.py", line 1792, in run
[[1;34m127.0.0.1/01/01-of-04[m::stderr]     return self._benchmark_train()
[[1;34m127.0.0.1/01/01-of-04[m::stderr]   File "/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn_kungfu.py", line 1975, in _benchmark_train
[[1;34m127.0.0.1/01/01-of-04[m::stderr]     build_result = self._build_graph()
[[1;34m127.0.0.1/01/01-of-04[m::stderr]   File "/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn_kungfu.py", line 2009, in _build_graph
[[1;34m127.0.0.1/01/01-of-04[m::stderr]     (input_producer_op, enqueue_ops, fetches) = self._build_model()
[[1;34m127.0.0.1/01/01-of-04[m::stderr]   File "/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn_kungfu.py", line 2762, in _build_model
[[1;34m127.0.0.1/01/01-of-04[m::stderr]     phase_train)
[[1;34m127.0.0.1/01/01-of-04[m::stderr]   File "/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn_kungfu.py", line 2840, in _build_fetches
[[1;34m127.0.0.1/01/01-of-04[m::stderr]     loss_scale_params)
[[1;34m127.0.0.1/01/01-of-04[m::stderr]   File "/benchmarks/scripts/tf_cnn_benchmarks/variable_mgr.py", line 110, in append_apply_gradients_ops
[[1;34m127.0.0.1/01/01-of-04[m::stderr]     self.grad_has_inf_nan)
[[1;34m127.0.0.1/01/01-of-04[m::stderr]   File "/benchmarks/scripts/tf_cnn_benchmarks/variable_mgr_util.py", line 112, in append_gradients_with_loss_scale
[[1;34m127.0.0.1/01/01-of-04[m::stderr]     training_ops.extend(get_apply_gradients_ops_func())
[[1;34m127.0.0.1/01/01-of-04[m::stderr]   File "/benchmarks/scripts/tf_cnn_benchmarks/variable_mgr.py", line 106, in get_apply_gradients_ops_func
[[1;34m127.0.0.1/01/01-of-04[m::stderr]     return [opt.apply_gradients(grads)]
[[1;34m127.0.0.1/01/01-of-04[m::stderr]   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/optimizer.py", line 610, in apply_gradients
[[1;34m127.0.0.1/01/01-of-04[m::stderr]     update_ops.append(processor.update_op(self, grad))
[[1;34m127.0.0.1/01/01-of-04[m::stderr]   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/optimizer.py", line 115, in update_op
[[1;34m127.0.0.1/01/01-of-04[m::stderr]     update_op = optimizer._apply_dense(g, self._v)  # pylint: disable=protected-access
[[1;34m127.0.0.1/01/01-of-04[m::stderr]   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/gradient_descent.py", line 60, in _apply_dense
[[1;34m127.0.0.1/01/01-of-04[m::stderr]     use_locking=self._use_locking).op
[[1;34m127.0.0.1/01/01-of-04[m::stderr]   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/gen_training_ops.py", line 577, in apply_gradient_descent
[[1;34m127.0.0.1/01/01-of-04[m::stderr]     use_locking=use_locking, name=name)
[[1;34m127.0.0.1/01/01-of-04[m::stderr]   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
[[1;34m127.0.0.1/01/01-of-04[m::stderr]     op_def=op_def)
[[1;34m127.0.0.1/01/01-of-04[m::stderr]   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
[[1;34m127.0.0.1/01/01-of-04[m::stderr]     return func(*args, **kwargs)
[[1;34m127.0.0.1/01/01-of-04[m::stderr]   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
[[1;34m127.0.0.1/01/01-of-04[m::stderr]     op_def=op_def)
[[1;34m127.0.0.1/01/01-of-04[m::stderr]   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1792, in __init__
[[1;34m127.0.0.1/01/01-of-04[m::stderr]     control_input_ops)
[[1;34m127.0.0.1/01/01-of-04[m::stderr]   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1631, in _create_c_op
[[1;34m127.0.0.1/01/01-of-04[m::stderr]     raise ValueError(str(e))
[[1;34m127.0.0.1/01/01-of-04[m::stderr] ValueError: Dimension 0 in both shapes must be equal, but are 512 and 64. Shapes are [512] and [64]. for 'append_apply_gradient_ops/GradientDescent/update_v0/cg/resnet_v115/conv51/batchnorm51/gamma/ApplyGradientDescent' (op: 'ApplyGradientDescent') with input shapes: [512], [], [64].
[kungfu-prun] 2019/04/05 16:23:52 [1;35m[E][m #127.0.0.1/03/03-of-04 exited with error: exit status 1
[kungfu-prun] 2019/04/05 16:23:53 [1;35m[E][m #127.0.0.1/00/00-of-04 exited with error: exit status 1
[kungfu-prun] 2019/04/05 16:23:53 [1;35m[E][m #127.0.0.1/02/02-of-04 exited with error: exit status 1
[kungfu-prun] 2019/04/05 16:23:53 [1;35m[E][m #127.0.0.1/01/01-of-04 exited with error: exit status 1
[kungfu-prun] 2019/04/05 16:23:53 all 4/4 local peers finished, took 9.043927896s
[kungfu-prun] 2019/04/05 16:23:53 exit on error: 4 peers failed
